name: Send Slack message
on:
  issues:
    types: [opened]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: post slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          slack-message: |
              "new issue: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }} created."
          channel-id: ${{ secrets.SLACK_CHANNEL_TESTER }}
