name: Model Test on PR

on: 
  pull_request:

jobs:
  test:
    if: github.repository != 'ersilia-os/eos-template'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3.5.2
        with:
          lfs: true
      
      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH
      
      - name: Source conda
        run: source $CONDA/etc/profile.d/conda.sh
        
      - name: Set Python to 3.10.10
        run:
         conda install -y python=3.10.10 
      
      - name: Install dependencies
        run: |
          source activate
          conda init
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge

      - name: Install ersilia
        run: |
          source activate
          python --version
          echo "After conda init"
          conda init
          python -m pip install git+https://github.com/ersilia-os/ersilia.git
  
      - name: Check metadata before updating to AirTable
        id: check-metadata
        env:
          USER_NAME: ${{ github.event.pull_request.head.repo.owner.login }}
          BRANCH: "main"
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          source activate
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/update_metadata_to_airtable.py
          python3 update_metadata_to_airtable.py $USER_NAME $REPO_NAME $BRANCH

      - name: Predict output
        env:
          MODEL_ID: ${{ github.event.repository.name }}
        run: |
          source activate
          echo "Sample model id selected: $MODEL_ID"
          ersilia -v fetch $MODEL_ID --repo_path .
          ersilia -v serve $MODEL_ID
          ersilia sample -n 5 -f input.csv
          ersilia -v api -i input.csv
          ersilia close
          
      - name: Upload log output
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb #pin v3.1.1
        with:
          name: debug-logs
          retention-days: 1
          path: /home/runner/eos/console.log
